# Generated by Django 2.2.2 on 2019-06-19 10:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('alt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_dt', models.DateTimeField(verbose_name='init date')),
                ('fin_dt', models.DateTimeField(verbose_name='final date')),
                ('values', jsonfield.fields.JSONField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicing.Station')),
            ],
        ),
    ]
