# Generated by Django 2.2.2 on 2019-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
