# Generated by Django 2.2.2 on 2019-06-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicing', '0002_auto_20190619_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikes_available', models.IntegerField(default=0)),
                ('mech_bikes_available', models.IntegerField(default=0)),
                ('electric_bikes_available', models.IntegerField(default=0)),
                ('docks_available', models.IntegerField(default=0)),
                ('historic_datetime', models.DateTimeField(verbose_name='timestamp')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicing.Station')),
            ],
        ),
    ]
